#server:
#  port: 8082
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    fetch-registry: true
#    register-with-eureka: true
#
#spring:
#  application:
#    name: person
#  data:
#    mongodb:
#      authentication-database: admin
#      username: rootuser
#      password: rootpass
#      database: person
#      port: 27017
#      host: localhost

server.error.include-message: always
spring.application.name: person
#^this is what we are calling this microservice (has to be same as config (which is called person.yml))
spring.config.import: optional:configserver:http://config-server:8888
#^this is telling the application where to find the config files