spring.cloud.config.server.git.uri: ${HOME}/Documents/config_repo
  #convention is port 8888 for config servers
  #the endpoint to access is http://localhost:8888/<file-name>/<profile>
  #if no explicit profile set then it will be 'default'
server.port: 8888
spring.cloud.config.server.git.default-label: main